# Generated by Django 5.0.2 on 2024-12-06 15:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название план')),
                ('start_period', models.DateField(verbose_name='Начало период')),
                ('period_end', models.DateField(verbose_name='Конец период')),
                ('plan_type', models.CharField(choices=[('perspective', 'Перспективный'), ('current', 'Текущий'), ('operational', 'Оперативный')], max_length=20, verbose_name='Тип')),
            ],
            options={
                'verbose_name': 'Финансовый план',
                'verbose_name_plural': 'Финансовые планы',
            },
        ),
        migrations.CreateModel(
            name='Financial_Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.DateField(verbose_name='Период')),
                ('actual_income_expence', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Реальные доходы/расходы')),
                ('deviation', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Отклонение от плана')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.financialplan', verbose_name='План')),
            ],
        ),
        migrations.CreateModel(
            name='BudjetItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('types', models.CharField(choices=[('income', 'Доход'), ('expense', 'Расход')], max_length=16, verbose_name='Тип')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Сумма')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.financialplan', verbose_name='План')),
            ],
        ),
        migrations.CreateModel(
            name='Forecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forecast_amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Прогнозируемая сумма')),
                ('method', models.CharField(choices=[('regression', 'Регрессия'), ('time_series', 'Временные ряды'), ('other', 'Другие методы')], max_length=20, verbose_name='Метод прогнозирования')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.financialplan', verbose_name='План')),
            ],
        ),
    ]
